-- 코드를 입력하세요
SELECT
    p.PRODUCT_CODE,
    SUM(p.PRICE * SALES_AMOUNT) AS REVENUE
FROM PRODUCT p
JOIN OFFLINE_SALE o
    ON p.PRODUCT_ID = o.PRODUCT_ID
    GROUP BY p.PRODUCT_CODE
    ORDER BY REVENUE DESC, p.PRODUCT_CODE ASC;